github_actions:
  - '.github/workflows/*'
generator:
  - 'openapi-generator/*'
annotations:
  - 'openapi-generator-annotations/*'
cli:
  - 'openapi-generator-cli/*'
docs:
  - 'README.md'
  - 'CHANGELOG.md'
  - 'LICENSE'
