name: openapi_generator_annotations
description: Annotation package for openapi_generator https://pub.dev/packages/openapi_generator.
version: 4.12.0
homepage: https://github.com/gibahjoe/openapi-generator-dart


environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test:
  source_gen_test: ^1.0.6
  lint:
