name: openapi_generator_cli
description: A dart wrapper around openapi-generator inspired by the node implementation.
version: 3.0.1
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.12.1 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8

executables:
  openapi-generator: main
