name: openapi_generator
description: Generator for openapi client sdk inspired by the npm implementation of openapi-generator-cli.
version: 3.1.3
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: '>=0.12.6 <=2.0.1'
  source_gen: ^1.0.0
  path: ^1.8.0
  openapi_generator_annotations: ^3.1.3
  analyzer: '>=1.4.0 <=1.5.0'
  openapi_generator_cli: ^3.1.3

dev_dependencies:
  pedantic: ^1.11.0
