name: openapi_generator
description: Generator for openapi client sdk inspired by the npm implementation of openapi-generator-cli.
version: 3.2.1
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.1.0
  source_gen: ^1.1.0
  path: ^1.8.0
  openapi_generator_annotations: ^3.2.1
  analyzer: ^2.2.0
  openapi_generator_cli: ^3.2.1

dev_dependencies:
  pedantic: ^1.11.1

