name: openapi_generator
description: Generator for openapi client sdk inspired by the npm implementation of openapi-generator-cli.
version: 3.0.1
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  build: '>=0.12.6 <=2.0.0'
  source_gen: ^0.9.10+3
  path: ^1.8.0
  openapi_generator_annotations: ^3.0.1
  analyzer: ^1.1.0
  openapi_generator_cli: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0
#  build_config: ^0.4.5
#  build_runner:
#  test: ^1.15.7
