name: openapi_generator
description: Generator for openapi client sdk inspired by the npm implementation of openapi-generator-cli.
version: 3.1.1-2
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: '>=0.12.6 <=2.0.0'
  source_gen: ^1.0.0
  path: ^1.8.0
  openapi_generator_annotations: ^3.1.0
  analyzer: ^1.3.0
  openapi_generator_cli: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
#  build_config: ^0.4.5
#  build_runner:
#  test: ^1.15.7
