name: Stable release 🕊️📦✅

on:
  release:
    types:
      - released # Trigger on stable releases
      - prereleased # Trigger on pre-releases (optional)
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    uses: gibahjoe/openapi-generator-dart/.github/workflows/code_quality.yml@master
    secrets: inherit # Reuse repository secrets

  publish_annotations:
    name: Publish Annotations Package
    needs: [test]
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: openapi-generator-annotations

  publish_cli:
    name: Publish CLI Package
    needs: [test]
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: openapi-generator-cli

  publish_generator:
    name: Publish Generator Package
    needs: [publish_cli, publish_annotations]
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: openapi-generator
