name: Stable release 🕊️📦

on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:

jobs:
  test:
    uses: gibahjoe/openapi-generator-dart/.github/workflows/code_quality.yml@master
  publish:
    name: Publish Packages with Melos
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: bluefireteam/melos-action@v3
      - name: Authenticate with Pub
        run: echo "${{ secrets.PUB_CREDENTIAL_JSON }}" > ~/.pub-cache/credentials.json
      - name: Publish
        run: melos publish --no-dry-run --yes
