name: release-please
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: github.event_name != 'pull_request' || (github.event.pull_request.merged && github.event.pull_request.head.ref !~ 'release-please/.*')
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.OG_BOT_TOKEN }}
