name: Stable release 🕊️📦✅

on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:

jobs:
  test:
    uses: gibahjoe/openapi-generator-dart/.github/workflows/code_quality.yml@master
    secrets: inherit
  publish:
    name: Publish Packages with Melos
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
      - uses: dart-lang/setup-dart@v1

      - name: Publish
        run: melos publish --no-dry-run --yes
